server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: service2_route
          uri: http://localhost:8082 # URL do microservice 2
          predicates:
            - Path=/email/**
